# Mind Project - 全局配置
project:
  name: "Mind - AI 技术追踪"
  root: "/Users/shenbo/Desktop/mind"

# Claude Code 模块配置
ccnews:
  github:
    repo: "anthropics/claude-code"
    lookback_days: 3
    heat_threshold: 30
    max_issues: 3

  hn:
    keywords: ["Claude Code"]
    lookback_days: 7
    heat_threshold: 70
    max_discussions: 2

  database:
    path: "cc/ccnews.db"

  cache:
    path: "cc/.meta/cache/daily_data.json"

  reports:
    path: "cc/{date}/index.md"
    target_lines: 100
    range: [80, 120]

# AI 全景模块配置
ainews:
  sources:
    - name: "LMSYS Arena"
      url: "https://chat.lmsys.org/"
      type: "leaderboard"

    - name: "Hacker News"
      url: "https://news.ycombinator.com/"
      keywords: ["AI", "LLM", "GPT", "Claude", "Gemini"]
      min_points: 50

    - name: "Reddit"
      subreddits: ["artificial", "LocalLLaMA"]
      min_upvotes: 100

    - name: "Anthropic Blog"
      url: "https://www.anthropic.com/news"

    - name: "OpenAI Blog"
      url: "https://openai.com/blog"

  cache:
    path: "ainews/.meta/cache/ai_data.json"

  reports:
    path: "ainews/{date}/index.md"
    target_lines: 100
    range: [80, 120]

# 工具配置
tools:
  request_timeout: 10
  max_retries: 3
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"

# 归档配置
archive:
  enabled: true
  keep_days: 30
  archive_path: "{module}/archive/{year}-{month}/"

# 邮件推送配置
email:
  enabled: false  # 设置为 true 启用邮件推送

  # SMTP 服务器配置（请根据你的邮箱服务商配置）
  smtp:
    # 常见邮箱配置示例：
    # Gmail: smtp.gmail.com, 587
    # QQ邮箱: smtp.qq.com, 587
    # 163邮箱: smtp.163.com, 465
    # Outlook: smtp-mail.outlook.com, 587
    host: "smtp.example.com"  # SMTP 服务器地址
    port: 587                  # SMTP 端口（587=TLS, 465=SSL）
    use_tls: true             # 是否使用 TLS
    use_ssl: false            # 是否使用 SSL（与 TLS 二选一）

  # 发件人信息（需要配置）
  sender:
    email: "your-email@example.com"     # 发件人邮箱
    password: ""                         # 邮箱密码或应用专用密码（建议使用环境变量）
    name: "Mind AI Report"              # 发件人显示名称

  # 收件人列表
  recipients:
    - "your-email@example.com"          # 可以添加多个收件人

  # 邮件内容配置
  content:
    subject_prefix: "[Mind Report]"     # 邮件主题前缀
    send_ccnews: true                   # 发送 Claude Code 日报
    send_ainews: true                   # 发送 AI 全景日报
    format: "html"                      # 邮件格式: html 或 plain
    attach_markdown: false              # 是否附加原始 Markdown 文件

  # 发送时机
  schedule:
    ccnews: "daily"      # 发送频率: daily, weekly, manual
    ainews: "daily"
    time: "09:00"        # 发送时间（24小时制）
